version: '2'
services:
  nginx:
    image: nginx
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/nginx/template:/etc/nginx/template:ro
      - $PWD/certs:/etc/letsencrypt:ro
      - $PWD/www:/usr/share/nginx/html:ro
    ports:
      - '80:80'
      - '443:443'
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf && openssl dhparam 2048 -out /etc/nginx/ssl/dhparam.pem && nginx -g 'daemon off;'"
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    depends_on:
      - nginx
    env_file:
      - .env
    volumes:
      - $PWD/www:/var/www/html
      - $PWD/certs/live:/etc/letsencrypt/live
      - $PWD/certs:/var/lib/letsencrypt
    command:  bash -c "certbot certonly --webroot --text --agree-tos --email $HOST_EMAIL --rsa-key-size 4096 --renew-by-default -w /var/www/html -d $NGINX_HOST --verbose"
