version: '2'
services:
  letsencrypt:


  nginx:
    image: nginx
    depends_on:
      - letsencrypt
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/nginx/template:/etc/nginx/template:ro
      - $PWD/www:/usr/share/nginx/html:ro
    ports:
      - '80:80'
      - '443:443'
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf && openssl dhparam 2048 -out /etc/nginx/ssl/dhparam.pem && nginx -g 'daemon off;'"

app:
  image
  php:
    build: ./php
    ports:
      - '80:80'
    depends_on:
      - mysql
    links:
      - mysql:mysql.db
    env_file:
      - .env
    environment:
      - DB_HOST=mysql.db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/www:/var/www/html
      - $PWD/php/log:/var/log/apache2
      - $PWD/php/conf:/usr/local/etc/php
