version: '2'
services:
  nginx:
    build: nginx
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/nginx/template:/etc/nginx/template:ro
      - $PWD/www:/usr/share/nginx/html:ro
    volumes_from:
      - letsencrypt:ro
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - letsencrypt
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf && openssl dhparam 2048 -out /etc/nginx/ssl/dhparam.pem && nginx -g 'daemon off;'"
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt
      - /var/lib/letsencrypt
    ports:
      - '80'
      - '443'
    command:  bash -c "certbot certonly --standalone --text --agree-tos --rsa-key-size 4096 --force-renewal -d $NGINX_HOST --verbose"
